version: '3.8'

services:
    nginx:
      container_name: nginx
      build:
        context: docker
        dockerfile: dev/nginx/Dockerfile
      volumes:
        - ./app:/app
      ports:
        - "80:80"
      depends_on:
        - postgresql

    php-fpm:
      container_name: fpm
      build:
        context: docker
        dockerfile: dev/php-fpm/Dockerfile
      volumes:
        - ./app:/app
      environment:
        APP_DEBUG: 1
        POSTGRES_HOST: postgresql
        POSTGRES_USER: app
        POSTGRES_DB: app
        POSTGRES_PASSWORD: password
      depends_on:
        - nginx

    php-cli:
      container_name: cli
      build:
        context: docker
        dockerfile: dev/php-cli/Dockerfile
      volumes:
        - ./app:/app
      environment:
        POSTGRES_HOST: postgresql
        POSTGRES_USER: app
        POSTGRES_DB: app
        POSTGRES_PASSWORD: password

    postgresql:
      container_name: postgresql
      image: postgres:16-alpine3.18
      environment:
        POSTGRES_HOST: postgresql
        POSTGRES_USER: app
        POSTGRES_DB: app
        POSTGRES_PASSWORD: password
      volumes:
        - ./docker/postgresql:/var/lib/postgresql/data
      ports:
        - "5432:5432"

    rabbitmq:
      container_name: rabbitmq
      image: rabbitmq:3.10.6-management-alpine
      hostname: my-rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
      volumes:
        - './docker/rabbitmq:/var/lib/rabbitmq/mnesia'
      ports:
        - "5672:5672"
        - "15672:15672"


    worker:
      container_name: worker
      build:
        context: docker
        dockerfile: dev/worker/Dockerfile
      volumes:
        - ./worker:/app
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
      depends_on:
        - rabbitmq
